CREATE TABLE FUENTE (
    id TEXT NOT NULL,
    fuente TEXT NOT NULL,
    via    TEXT NOT NULL,
    fecha  DATE NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE PAIS (
    id INTEGER NOT NULL,
    txt TEXT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE PROVINCIA (
    id INTEGER NOT NULL,
    txt TEXT NOT NULL,
    pais INTEGER NOT NULL REFERENCES PAIS(id),
    PRIMARY KEY (id)
);

CREATE TABLE LOCALIDAD (
    id INTEGER NOT NULL,
    localidad INTEGER NOT NULL,
    txt TEXT NOT NULL,
    provincia INTEGER NOT NULL REFERENCES PROVINCIA(id),
    UNIQUE (localidad, provincia)
    PRIMARY KEY(id)
);

CREATE TABLE MINISTERIO (
    id INTEGER NOT NULL,
    txt TEXT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE CENTRO (
    id INTEGER NOT NULL,
    txt TEXT NOT NULL,
    ministerio INTEGER NOT NULL REFERENCES MINISTERIO(id),
    PRIMARY KEY (id)
);

CREATE TABLE UNIDAD (
    id INTEGER NOT NULL,
    txt TEXT NOT NULL,
    centro INTEGER NOT NULL REFERENCES CENTRO(id),
    localidad INTEGER NOT NULL REFERENCES LOCALIDAD(id),
    PRIMARY KEY (id)
);

CREATE TABLE TIPO_PUESTO (
    id TEXT NOT NULL,
    txt TEXT NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE PROVISION (
    id TEXT NOT NULL,
    txt TEXT NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE ADMINISTRACION (
    id TEXT NOT NULL,
    txt TEXT NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE FORMACION (
    id INTEGER NOT NULL,
    txt TEXT NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE TITULACION (
    id TEXT NOT NULL,
    txt TEXT NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE GRUPO (
    id TEXT NOT NULL,
    base REAL NOT NULL,
    trienio REAL NOT NULL,
    extra_base REAL NOT NULL,
    extra_trienio REAL NOT NULL,
    muface_cotizacion REAL NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE CUERPO (
    id TEXT NOT NULL,
    txt TEXT NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE OBSERVACION (
    id TEXT NOT NULL,
    txt TEXT NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE CARGO (
    id INTEGER NOT NULL,
    txt TEXT NOT NULL,
    UNIQUE (txt),
    PRIMARY KEY(id)
);

CREATE TABLE NIVEL (
    id INTEGER NOT NULL,
    destino REAL NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE PUESTO (
    id INTEGER NOT NULL,
    cargo INTEGER NOT NULL REFERENCES CARGO(id),
    unidad INTEGER NOT NULL REFERENCES UNIDAD(id),
    localidad INTEGER NOT NULL REFERENCES LOCALIDAD(id),
    nivel INTEGER NOT NULL REFERENCES NIVEL(id),
    especifico REAL NOT NULL,
    tipo TEXT REFERENCES TIPO_PUESTO(id),
    provision TEXT REFERENCES PROVISION(id),
    administracion TEXT REFERENCES ADMINISTRACION(id),
    formacion INTEGER REFERENCES FORMACION(id),
    vacante INTEGER NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE PUESTO_GRUPO (
    puesto INTEGER NOT NULL REFERENCES PUESTO(id),
    grupo TEXT NOT NULL REFERENCES GRUPO(id),
    PRIMARY KEY(puesto, grupo)
);

CREATE TABLE PUESTO_OBSERVACION (
    puesto INTEGER NOT NULL REFERENCES PUESTO(id),
    observacion TEXT NOT NULL REFERENCES OBSERVACION(id),
    PRIMARY KEY(puesto, observacion)
);
CREATE TABLE PUESTO_CUERPO (
    puesto INTEGER NOT NULL REFERENCES PUESTO(id),
    cuerpo TEXT NOT NULL REFERENCES CUERPO(id),
    PRIMARY KEY(puesto, cuerpo)
);
CREATE TABLE PUESTO_TITULACION (
    puesto INTEGER NOT NULL REFERENCES PUESTO(id),
    titulacion TEXT NOT NULL REFERENCES TITULACION(id),
    PRIMARY KEY(puesto, titulacion)
);

